name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: |
          chmod a+x ./gradlew
          ./gradlew test
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/test/jacocoTestReport.xml

  deploy:
    if: github.ref == 'refs/heads/master' && success()
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup SSH and deploy to Dokku
        env:
          SSH_KEY: ${{ secrets.DOKKU_SSH_KEY }}
        run: |
          which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)
          eval $(ssh-agent -s)
          echo "$SSH_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan "vps.florent.best" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          git remote add dokku dokku@vps.florent.best:vaccines
          git push dokku master